### ISSUE TITLE
Fix taking screenshots from emulator

### ISSUE THREAD

**Issue by QZenn** [QZenn/podcas-t#4]
Running tests

$ adb shell am instrument -w -r   -e debug false -e class com.qzenn.podcast.testSuite.scenarioTest.MainTest#testResumeActivty com.qzenn.podcast.test/android.support.test.runner.AndroidJUnitRunner
Client not ready yet..Waiting for process to come online
Connected to process 5945 on device Galaxy_Nexus_API_23 [emulator-5554]
Test running started

java.lang.RuntimeException: Unable to capture screenshot.
at com.squareup.spoon.Spoon.screenshot(Spoon.java:87)
at com.squareup.spoon.Spoon.screenshot(Spoon.java:60)
at com.qzenn.podcast.util.Util.takeScreenshot(Util.java:64)
at com.qzenn.podcast.util.Util.takeScreenshot(Util.java:59)
at com.qzenn.podcast.screen.ScrMain.<init>(ScrMain.java:22)
at com.qzenn.podcast.testSuite.scenarioTest.MainTest.testResumeActivty(MainTest.java:74)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
Caused by: java.lang.IllegalAccessException: Unable to create output dir: /storage/emulated/0/app_spoon-screenshots
at com.squareup.spoon.Spoon.createDir(Spoon.java:262)
at com.squareup.spoon.Spoon.createDir(Spoon.java:259)
at com.squareup.spoon.Spoon.createDir(Spoon.java:259)
at com.squareup.spoon.Spoon.filesDirectory(Spoon.java:224)
at com.squareup.spoon.Spoon.obtainScreenshotDirectory(Spoon.java:140)
at com.squareup.spoon.Spoon.screenshot(Spoon.java:78)
... 34 more

**Comment by QZenn** [comment]
For desktop at first
and Travis CI then.
